"""Verify the build123d stem against `../keycap_stem.scad` -- measured, not assumed.

Three checks, in increasing strength:

1. **Cross geometry**, sectioned off the real solid.  The recipe's rule is to measure
   the MX cross on the STEP rather than trust the constants, and that is exactly where
   trusting them goes wrong: `MX_CROSS` 4.35 / `MX_CROSS_WIDTH` 1.4 are the plus
   BEFORE `offset(r = -0.3)`, so the opening is 4.05 x 1.10.
2. **Volume + bounding box** against the OpenSCAD mesh of the same call.
3. **Boolean difference both ways** (A\\B and B\\A) through OpenSCAD -- the check that
   a matching volume cannot fake, since it localises any real disagreement.

    python verify.py            # both variants; needs `openscad` for check 3

⚠️ Reference meshes are exported with `txt = ""`.  The engraving is off in the STEP by
default (a tool feature, and font-dependent), so comparing against an engraved mesh
would charge the model ~5 mm3 of DejaVu-vs-Noto difference that is not a geometry error.
"""
import os, re, shutil, subprocess, struct, sys, tempfile

import numpy as np
from build123d import Plane, export_stl

import stem_model as sm

HERE = os.path.dirname(os.path.abspath(__file__))
SCAD_DIR = os.path.join(HERE, "..")
VOLUME_TOLERANCE = 0.01          # 1 %, per the recipe
DIFF_TOLERANCE = 0.005           # 0.5 % of part volume in either one-sided difference


# ---------------------------------------------------------------- mesh helpers
def mesh_stats(path):
    with open(path, "rb") as f:
        head = f.read(80)
        if head[:5] == b"solid" and b"facet" in f.read(400):
            f.seek(0)
            tris, cur = [], []
            for line in f:
                w = line.split()
                if w[:1] == [b"vertex"]:
                    cur.append([float(x) for x in w[1:4]])
                    if len(cur) == 3:
                        tris.append(cur); cur = []
            t = np.array(tris)
        else:
            f.seek(80)
            n = struct.unpack("<I", f.read(4))[0]
            d = np.frombuffer(f.read(n * 50), dtype=np.uint8).reshape(n, 50)
            t = d[:, 12:48].copy().view("<f4").reshape(n, 3, 3).astype(np.float64)
    vol = np.einsum("ij,ij->i", t[:, 0], np.cross(t[:, 1], t[:, 2])).sum() / 6.0
    v = t.reshape(-1, 3)
    return dict(tris=len(t), volume=vol, lo=v.min(0), hi=v.max(0))


def run_openscad(src, out, cwd):
    """Run OpenSCAD, distinguishing an EMPTY result from a real failure.

    Both exit 1 (CLAUDE.md), and an empty result writes no file -- which here is the
    GOOD outcome (a perfect boolean match), so getting this backwards would report a
    flawless model as a crash.
    """
    p = subprocess.run(["openscad", "-o", out, "--export-format", "binstl", src],
                       cwd=cwd, capture_output=True, text=True)
    log = p.stdout + p.stderr
    if "Current top level object is empty" in log:
        return None
    if p.returncode != 0 or not os.path.exists(out):
        raise RuntimeError(f"openscad failed:\n{log}")
    return out


def scad_reference(name, tmp):
    """Export `mx_stem(...)` straight from the .scad, one piece, un-engraved."""
    cfg = sm.VARIANTS[name]
    src = os.path.join(SCAD_DIR, f"_verify_{name}.scad")
    with open(src, "w") as f:
        f.write("// generated by step/verify.py -- safe to delete\n"
                "include <keycap_stem.scad>\n"
                f"mx_stem(u_size = {cfg['u_size']}, angle = {cfg['angle']}, "
                f"extra_len = {cfg['extra_len']}, txt = \"\");\n")
    out = os.path.join(tmp, f"ref_{name}.stl")
    try:
        # cwd is the .scad dir: `include <>` resolves relative to the FILE, so the
        # driver has to live beside keycap_stem.scad or it silently finds nothing.
        run_openscad(os.path.basename(src), out, SCAD_DIR)
    finally:
        os.remove(src)
    return out


def boolean_diff(a_stl, b_stl, tmp, tag):
    src = os.path.join(tmp, f"diff_{tag}.scad")
    with open(src, "w") as f:
        f.write(f'difference() {{\n  import("{a_stl}", convexity = 10);\n'
                f'  import("{b_stl}", convexity = 10);\n}}\n')
    out = run_openscad(src, os.path.join(tmp, f"diff_{tag}.stl"), tmp)
    return 0.0 if out is None else mesh_stats(out)["volume"]


# ------------------------------------------------------------ cross measurement
def measure_cross(part, z):
    """Section the solid at `z` and measure the cross opening in the stem."""
    sec = part & Plane.XY.offset(z)
    stem_face = min(sec.faces(), key=lambda f: f.bounding_box().size.X)
    inner = [w for w in stem_face.wires() if w.bounding_box().size.X < sm.MX_CYLINDER]
    if not inner:
        return None
    wire = inner[0]
    bb = wire.bounding_box()
    # Measure the arc radii instead of reading `Edge.radius`.  The fillet and relief
    # walls are oblique cones (tapering about the axis moves an off-centre arc's centre
    # as well as its radius), so OCCT types the section edges as B-splines and
    # `geom_type == CIRCLE` matches nothing -- reporting an empty radius list for a
    # part whose arcs are perfectly circular.  Three points on the edge give the radius.
    radii = []
    for e in wire.edges():
        if e.geom_type.name == "LINE":
            continue
        a, b, c = (e @ 0.0, e @ 0.5, e @ 1.0)
        radii.append(_circumradius(a, b, c))
    return dict(x=bb.size.X, y=bb.size.Y, radii=sorted({round(r, 4) for r in radii}),
                area=stem_face.area, wire_len=wire.length)


def _circumradius(a, b, c):
    a, b, c = (np.array([p.X, p.Y, 0.0]) for p in (a, b, c))
    ab, bc, ca = (np.linalg.norm(x - y) for x, y in ((a, b), (b, c), (c, a)))
    area2 = float(np.linalg.norm(np.cross(b - a, c - a)))
    return float("inf") if area2 < 1e-12 else float(ab * bc * ca / (2 * area2))


# -------------------------------------------------------------------- self-test
def self_test():
    """Prove the checks can FAIL -- the positive control CLAUDE.md asks for.

    A verification that has never rejected anything is indistinguishable from one
    that cannot.  This widens the MX cross by 0.10 mm -- a change a moulder would
    care about and an eyeball would not -- rebuilds, and asserts each check catches
    it.  It is also the check that would have caught the `Shape.scale()` centre bug
    on its own.
    """
    tmp = tempfile.mkdtemp(prefix="stem_selftest_")
    good = sm.build("S_1U")
    ref = scad_reference("S_1U", tmp)
    rs = mesh_stats(ref)

    saved = sm.MX_CROSS_WIDTH
    sm.MX_CROSS_WIDTH = saved + 0.10
    try:
        bad = sm.build("S_1U")
        m = measure_cross(bad, sm.MX_CROSS_FILLET)
        bad_stl = os.path.join(tmp, "bad.stl")
        export_stl(bad, bad_stl, tolerance=0.001, angular_tolerance=0.05)
        missing = boolean_diff(ref, bad_stl, tmp, "selftest")
        dv = abs(bad.volume - rs["volume"]) / rs["volume"]
    finally:
        sm.MX_CROSS_WIDTH = saved

    good_w = (saved - sm.MX_CROSS_FILLET)
    caught_cross = abs(m["y"] - 2 * max((sm.MX_CROSS - sm.MX_CROSS_FILLET) / 2,
                                        sm.MX_CROSS / 3 + good_w * 1.1 / 2)) > 2e-3
    caught_diff = missing / good.volume > DIFF_TOLERANCE / 10
    print("=== self-test: MX cross widened by 0.10 mm ===")
    print(f"  cross measurement differs : {caught_cross}")
    print(f"  SCAD \\ STEP grew to {missing:.4f} mm3 "
          f"({missing / good.volume * 100:.3f} %) : {caught_diff}")
    print(f"  volume delta {dv * 100:+.3f} % (still inside the 1 % gate: "
          f"{dv < VOLUME_TOLERANCE} -- so volume ALONE would MISS this)")
    ok = caught_cross and caught_diff
    print("\n=>", "PASS (the checks reject a wrong model)" if ok else "FAIL")
    return 0 if ok else 1


# ---------------------------------------------------------------------- driver
def main():
    if "--self-test" in sys.argv:
        return self_test()
    have_scad = shutil.which("openscad") is not None
    if not have_scad:
        print("!! openscad not on PATH -- skipping the boolean difference (check 3)")
    ok = True
    tmp = tempfile.mkdtemp(prefix="stem_verify_")
    for name, cfg in sm.VARIANTS.items():
        print(f"=== {name}  ({cfg['label']}) ===")
        part = sm.build(name)
        mine = os.path.join(tmp, f"mine_{name}.stl")
        export_stl(part, mine, tolerance=0.001, angular_tolerance=0.05)

        # 1 -- cross geometry
        for z, what in ((sm.MX_CROSS_FILLET, "above the lead-in chamfer"),
                        (5.0, "near the top of the stem")):
            m = measure_cross(part, z)
            taper = 1 - 0.03 * z / (2 * sm.STEM_HEIGHT)
            exp_l = (sm.MX_CROSS - sm.MX_CROSS_FILLET) * taper
            exp_w = (sm.MX_CROSS_WIDTH - sm.MX_CROSS_FILLET) * taper
            bulge = (sm.MX_CROSS_WIDTH - sm.MX_CROSS_FILLET) * 1.1 / 2 * taper
            exp_span = 2 * max(exp_l / 2, sm.MX_CROSS / 3 * taper + bulge)
            good = abs(m["x"] - exp_span) < 2e-3 and abs(m["y"] - exp_span) < 2e-3
            ok &= good
            print(f"  cross @ z={z:<5} {what}")
            print(f"    arms {m['x']:.4f} x {m['y']:.4f} mm  (expect {exp_span:.4f}; "
                  f"flats {exp_l:.4f} x {exp_w:.4f})  {'OK' if good else 'MISMATCH'}")
            want = sorted({round(sm.MX_CROSS_FILLET * taper, 4),
                           round(bulge, 4)})
            good = (len(m["radii"]) == len(want)
                    and all(abs(g - w) < 5e-4 for g, w in zip(m["radii"], want)))
            ok &= good
            print(f"    arc radii {[f'{r:.4f}' for r in m['radii']]} mm  "
                  f"(expect {[f'{r:.4f}' for r in want]}: the r{sm.MX_CROSS_FILLET} "
                  f"corner fillet and the relief bulges)  {'OK' if good else 'MISMATCH'}")

        if not have_scad:
            continue

        # 1b -- the cross cut against its own closed form.  A tapered prism's section
        # area scales as k(z)^2, so V = A0 * h * (1 - t + t^2/3) for a 1-t taper.  This
        # is the check that caught `Shape.scale()` defaulting to the shape's own centre
        # (see stem_model._taper_profile): the model stayed valid and the cross simply
        # tapered too slowly.
        h_cross, k = 2 * sm.STEM_HEIGHT, 0.97
        a0 = sm.cross_profile().area
        t = 1 - k
        want = a0 * h_cross * (1 - t + t * t / 3)
        got = sm.cross_cut(h_cross, k, 0.0).volume
        good = abs(got - want) / want < 1e-6
        ok &= good
        print(f"  cross prism volume {got:.6f} vs closed form {want:.6f}  "
              f"{'OK' if good else 'MISMATCH'}")

        # 2 -- volume + bbox against the .scad
        ref = scad_reference(name, tmp)
        rs = mesh_stats(ref)
        d = (part.volume - rs["volume"]) / rs["volume"]
        good = abs(d) < VOLUME_TOLERANCE
        ok &= good
        print(f"  volume  STEP {part.volume:.4f}  vs  SCAD mesh {rs['volume']:.4f}"
              f"   delta {d * 100:+.3f} %  {'OK' if good else 'MISMATCH'}")
        bb = part.bounding_box()
        db = max(abs(np.array([bb.min.X, bb.min.Y, bb.min.Z]) - rs["lo"]).max(),
                 abs(np.array([bb.max.X, bb.max.Y, bb.max.Z]) - rs["hi"]).max())
        good = db < 0.01
        ok &= good
        print(f"  bbox    max corner deviation {db:.5f} mm  {'OK' if good else 'MISMATCH'}")

        # 3 -- boolean difference both ways
        extra = boolean_diff(mine, ref, tmp, f"{name}_extra")
        missing = boolean_diff(ref, mine, tmp, f"{name}_missing")
        good = (max(extra, missing) / part.volume) < DIFF_TOLERANCE
        ok &= good
        print(f"  STEP \\ SCAD  {extra:8.4f} mm3 ({extra / part.volume * 100:.3f} %)")
        print(f"  SCAD \\ STEP  {missing:8.4f} mm3 ({missing / part.volume * 100:.3f} %)")
        print(f"    -> {'OK' if good else 'MISMATCH'}  (the residual is the .scad's "
              f"faceted cylinders: 128-gon stem, $fn=64 cross relief)")
    print("\n=>", "PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
